title: Arcanum Art
description: Digital Art Portfolio
baseurl: ""
url: "https://arcanumart.pics"

# Repository settings
repository: arcanum-art/arcanum-art-blog
github: [metadata]

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections settings
collections_dir: collections
collections:
  gallery:
    output: true
    permalink: /:collection/:name

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "gallery"
    values:
      layout: collection

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/