title: Arcanum Art
description: Digital Art Portfolio
baseurl: ""
url: "https://arcanumart.pics"

# Add these lines
repository: arcanum-art/arcanum-art-blog
github: [metadata]

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/